###

@url = http://localhost:8080/api/auth
###
GET {{url}} HTTP/1.1

### register
POST {{url}}/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "username": "user2",
  "password": "12345678",
  "email": "user2@gmail.com",
  "phoneNumber": "0989098919"
}

### login
POST {{url}}/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "12345678"
}